### ISSUE TITLE
resizing of widget.

### ISSUE THREAD

**Issue by bsutton** [cgustav/lite_rolling_switch#1]
Do you have an ETA on resizing of the widget?

**Comment by bawantha** [comment]
this is importent

**Comment by cgustav** [comment]
that cannot be done yet.
Since the repo is having more reception, implement this feature as soon as possible.
thanks.

**Comment by Automatik** [comment]
I made a PR to solve this issue.
#8

**Comment by subzero911** [comment]
It is possible to resize it with SizedBox.
But its content will remain unscaled.

**Comment by cgustav** [comment]
thanks to @Automatik contribution this issue is now solved. Please check the [last version release](https://github.com/cgustav/lite_rolling_switch/releases/tag/v1.0.0).

My apologies for the late response guys
