### ISSUE TITLE
Intento redibujar el widget y no me lo permite

### ISSUE THREAD

**Issue by Miller9921** [cgustav/lite_rolling_switch#11]
LiteRollingSwitch _buttom() {
    return LiteRollingSwitch(
  
  value:  poput,
  textOn: 'Disponible',
  textOff: 'Ocupado',
  colorOn: Colors.greenAccent[700],
  colorOff: Colors.redAccent[700],
  iconOn: Icons.done,
  iconOff: Icons.remove_circle_outline,
  textSize: 15.0,
  onChanged: (bool valor){
    setState(() {
     poput = valor;
    });
      
    
  },
 
  
);
  }

y sin el setState no hace nada pero si esta cambiando el valor del value

**Comment by cgustav** [comment]
@Miller9921 probablemente este bug ya ha sido corregido en https://github.com/cgustav/lite_rolling_switch/pull/6 

Siéntete libre de abrir otro hilo en caso de no ser resuelto tu problema. Te ofrezco mil disculpas en la demora en la respuesta.
