### ISSUE TITLE
null-safety

### ISSUE THREAD

**Issue by yakupbaser** [cgustav/lite_rolling_switch#13]
hi, is there any null-safety update?

**Comment by jamescardona11** [comment]
- I forked this project, last year I tried to integrate with this package, but I couldn't.
- I pushed a null safety version.
- Add new functionalities.
- Fell free to check: https://github.com/jamescardona11/rolling_switch

**Comment by Spiritfaer** [comment]
Hi there, maybe something is known about the move to null-safety?

**Comment by jamescardona11** [comment]
https://pub.dev/packages/rolling_switch

**Comment by cgustav** [comment]
@yakupbaser [a new version](https://github.com/cgustav/lite_rolling_switch/releases/tag/v1.0.0) was released today with a complete null safety support. I hope this helps and my apologize for you all for the late response.
