### ISSUE TITLE
Active icon is different size than inactive icon

### ISSUE THREAD

**Issue by cmenkemeller** [cgustav/lite_rolling_switch#14]
Currently, active icon size is 21 (line 180) and inactive icon size is 25 (line 182).

These should probably be the same size.

**Comment by jamescardona11** [comment]
I forked this project, last year I tried to integrate with this package, but I couldn't.
I pushed a null safety version.
Add new functionalities.
Fell free to check: https://github.com/jamescardona11/rolling_switch

**Comment by cgustav** [comment]
Hi dude, lot of improvements were added in the past release. I hope this could help you. Feel free to open a new issue if you want some help.
