### ISSUE TITLE
Too big

### ISSUE THREAD

**Issue by shasank-periwal** [cgustav/lite_rolling_switch#16]
The size of the switch is too big, can' t lower down its height and width.
If I do try to lessen them by wrapping them inside the container then things get squeezed.

**Comment by cgustav** [comment]
Hello @shasank27 . I'm aware of this limitation and the readme warns you about this.
A new version was released today and now you can change the component width but not the height, I'll release a new version as soon this behavior is fixed. My apologizes for the late response.
