### ISSUE TITLE
on change function is being called on load

### ISSUE THREAD

**Issue by MasterNeuromancer** [cgustav/lite_rolling_switch#2]
when the widget loads, the state is false, and therefore unintended calls are being made on the app. Is there a way to isolate the on tap function only. I only want the calls to be made when a user taps the widget, not on load. Thank you.

**Comment by Bader-Al** [comment]
I had the same issue and found two solutions.. however, the second one destroyed the drag of a DraggableBottomSheet I have in my app.. So i stuck to the first one

1 - just wrap the onChanged function with WidgetsBinding as such :
```
WidgetsBinding.instance.addPostFrameCallback((_){

  // Add Your Code here.

});
```

2- the other method is to use SchedulerBinding : 
```
SchedulerBinding.instance.addPostFrameCallback((_) {

  // add your code here.
});
```

**Comment by Bader-Al** [comment]
Incase you'd like to see where i found those solutions :
https://stackoverflow.com/questions/47592301/setstate-or-markneedsbuild-called-during-build

**Comment by MasterNeuromancer** [comment]
Thanks @Bader-Al , I will look into that!

**Comment by rodrigobastosv** [comment]
I just made a PR to solve this issue.

https://github.com/cgustav/lite_rolling_switch/pull/6

**Comment by Huzaifa2019** [comment]
Thank you so much

**Comment by 0ne0rZer0** [comment]
I was having the same problem what i did was add an if condition inside the _determine() function (as it is called during initState) 
` if (changeState) widget.onChanged(turnState);`
