### ISSUE TITLE
Intl 0.18.0

### ISSUE THREAD

**Issue by ninjagaru** [cgustav/lite_rolling_switch#21]
Is it possible to update intl dependency to the newest version 0.18.0
Than you

**Comment by cgustav** [comment]
Hello, Intl dependency has been updated in the latest version of the package.

Cheers!

**Comment by rekire** [comment]
@cgustav this change caused a dependency hell for me I cannot use your widget. There are lots of transitive dependencies which require the older version

```
Running "flutter pub get" in pos_app...
Resolving dependencies...
Because every version of flutter_localizations from sdk depends on intl 0.17.0 and lite_rolling_switch >=1.0.1 depends on intl ^0.18.0, flutter_localizations from sdk is incompatible with lite_rolling_switch >=1.0.1.
So, because pos_app depends on both flutter_localizations from sdk and lite_rolling_switch ^1.0.1, version solving failed.
pub get failed
...
```

Has this change and real reason except that this would be simply the latest version? When @ninjagaru wants to use a newer version he should be able to put it into his `pubspec.yaml`.

**Comment by cgustav** [comment]
I added it to avoid warnings and other messages from newer Flutter SDK versions. So feel free to downgrade.

Cheers
