### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ilusi0n** [cgustav/lite_rolling_switch#3]
What kind of licence this project has?
Thank you!

**Comment by Gensjava** [comment]
Hi guys I have a simple question is this a free thing? I just didn't find a description of the license something.

**Comment by cgustav** [comment]
Hello @ilusi0n @Gensjava  [a new version](https://github.com/cgustav/lite_rolling_switch/releases/tag/v1.0.0) was released today, the project is now supported by MIT license, feel free to use this library according to your needs. My apologies for the late response guys.
