### ISSUE TITLE
Size of Icon can't be changed

### ISSUE THREAD

**Issue by sidhagarwal05** [cgustav/lite_rolling_switch#7]

**Comment by NaseerUllahAwan** [comment]
size can not change

**Comment by NaseerUllahAwan** [comment]
The size is too big

**Comment by NaseerUllahAwan** [comment]
I like this switch but it will be better to have a small size. Like it can be shrinkable.

**Comment by MukunndPradhaan** [comment]
Please wrap the switch widget by a container with a specific height & width

**Comment by cgustav** [comment]
Hi guys @MySelfMukund is a very good suggestion.

Unfortunately you can't resize icons without causing a direct impact on the properties of the entire component.

Anyway today a [new version of the component](https://github.com/cgustav/lite_rolling_switch/releases/tag/v1.0.0) has been released where you can freely change the width.
