### ISSUE TITLE
[Request] Turn off rolling animation 

### ISSUE THREAD

**Issue by subzero911** [cgustav/lite_rolling_switch#9]
At first, thank you for the great package!
Could you add a parameter to turn off rolling animation? I want just to have a custom icon on a knob, and don't want this fancy rolling.

**Comment by Automatik** [comment]
In the meantime you can set the animation duration to zero.
`animationDuration: Duration(seconds: 0)`

**Comment by subzero911** [comment]
In this case, the knob translation animation will disappear too. It will just jump to "on/off" position.
I want to keep knob translation but get rid off rolling.

**Comment by sureshkumar-skc** [comment]
@Automatik Any progress on this ?

**Comment by Automatik** [comment]
You can replace the `CurvedAnimation` object with another one that you prefer and assign it to the `animation` variable. Or in the `animationController`'s listener, in the `setState` method, assign to the `value` variable the value that you want at every transition.

**Comment by cgustav** [comment]
In case any of you still want a solution to this I could work on it and release a new version asap. In the meantime I offer you my apologies for the late response.

**Comment by cgustav** [comment]
More improvements were added in the past release. I close this discussion due to inactivity.

_Cheers_
